"""Enterprise Schema initialization

Revision ID: 5fec47ea8082
Revises: 
Create Date: 2026-03-28 03:20:11.818330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fec47ea8082'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('send_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mailbox_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('target_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('smtp_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ai_summaries', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('ai_summaries', sa.Column('intent', sa.String(), nullable=True))
    op.add_column('ai_summaries', sa.Column('tone', sa.String(), nullable=True))
    op.add_column('ai_summaries', sa.Column('extracted_entities', sa.JSON(), nullable=True))
    op.add_column('ai_summaries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('ai_summaries', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('ai_summaries', 'thread_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_ai_summaries_id'), table_name='ai_summaries')
    op.drop_constraint(op.f('ai_summaries_thread_id_fkey'), 'ai_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'ai_summaries', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ai_summaries', 'intent_classification')
    op.drop_column('ai_summaries', 'summary_text')
    op.add_column('campaign_leads', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('campaign_leads', sa.Column('replied_at', sa.DateTime(), nullable=True))
    op.add_column('campaign_leads', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('campaign_leads', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('campaign_leads', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('campaign_leads', 'campaign_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('campaign_leads', 'contact_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_campaign_leads_id'), table_name='campaign_leads')
    op.drop_constraint(op.f('campaign_leads_campaign_id_fkey'), 'campaign_leads', type_='foreignkey')
    op.drop_constraint(op.f('campaign_leads_contact_id_fkey'), 'campaign_leads', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_leads', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'campaign_leads', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.add_column('campaigns', sa.Column('status', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('template_subject', sa.String(), nullable=False))
    op.add_column('campaigns', sa.Column('template_body', sa.Text(), nullable=False))
    op.add_column('campaigns', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('campaigns', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('campaigns', 'mailbox_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_constraint(op.f('campaigns_mailbox_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'mailboxes', ['mailbox_id'], ['id'], ondelete='SET NULL')
    op.drop_column('campaigns', 'subject_template')
    op.drop_column('campaigns', 'body_template')
    op.drop_column('campaigns', 'is_active')
    op.add_column('contacts', sa.Column('source', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('contacts', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('contacts', 'status',
               existing_type=postgresql.ENUM('NEW', 'CONTACTED', 'REPLIED', 'UNSUBSCRIBED', name='contactstatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.add_column('domains', sa.Column('status', sa.String(), nullable=True))
    op.add_column('domains', sa.Column('spf_status', sa.String(), nullable=True))
    op.add_column('domains', sa.Column('dkim_status', sa.String(), nullable=True))
    op.add_column('domains', sa.Column('dmarc_status', sa.String(), nullable=True))
    op.add_column('domains', sa.Column('mx_status', sa.String(), nullable=True))
    op.add_column('domains', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('domains', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_column('domains', 'is_active')
    op.add_column('mailboxes', sa.Column('display_name', sa.String(), nullable=False))
    op.add_column('mailboxes', sa.Column('smtp_username', sa.String(), nullable=False))
    op.add_column('mailboxes', sa.Column('smtp_password_encrypted', sa.String(), nullable=False))
    op.add_column('mailboxes', sa.Column('imap_username', sa.String(), nullable=False))
    op.add_column('mailboxes', sa.Column('imap_password_encrypted', sa.String(), nullable=False))
    op.add_column('mailboxes', sa.Column('daily_send_limit', sa.Integer(), nullable=True))
    op.add_column('mailboxes', sa.Column('current_warmup_stage', sa.Integer(), nullable=True))
    op.add_column('mailboxes', sa.Column('status', sa.String(), nullable=True))
    op.add_column('mailboxes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('mailboxes', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('mailboxes', 'domain_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('mailboxes', 'smtp_host',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mailboxes', 'smtp_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mailboxes', 'imap_host',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mailboxes', 'imap_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_mailboxes_id'), table_name='mailboxes')
    op.drop_constraint(op.f('mailboxes_domain_id_fkey'), 'mailboxes', type_='foreignkey')
    op.create_foreign_key(None, 'mailboxes', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mailboxes', 'password')
    op.drop_column('mailboxes', 'daily_limit')
    op.drop_column('mailboxes', 'is_active')
    op.add_column('messages', sa.Column('mailbox_id', sa.UUID(), nullable=False))
    op.add_column('messages', sa.Column('direction', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('to_emails', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('cc_emails', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('bcc_emails', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('subject', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('text_body', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('html_body', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('message_id_header', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('references_header', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('status', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('messages', 'thread_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.create_index(op.f('ix_messages_in_reply_to'), 'messages', ['in_reply_to'], unique=False)
    op.create_index(op.f('ix_messages_message_id_header'), 'messages', ['message_id_header'], unique=False)
    op.drop_constraint(op.f('messages_thread_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'mailboxes', ['mailbox_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'to_email')
    op.drop_column('messages', 'is_from_me')
    op.drop_column('messages', 'text_content')
    op.drop_column('messages', 'html_content')
    op.drop_column('messages', 'message_id')
    op.add_column('threads', sa.Column('external_thread_id', sa.String(), nullable=True))
    op.add_column('threads', sa.Column('participants', sa.JSON(), nullable=True))
    op.add_column('threads', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('threads', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('threads', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('threads', 'mailbox_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_threads_id'), table_name='threads')
    op.create_index(op.f('ix_threads_external_thread_id'), 'threads', ['external_thread_id'], unique=False)
    op.drop_constraint(op.f('threads_contact_id_fkey'), 'threads', type_='foreignkey')
    op.drop_constraint(op.f('threads_mailbox_id_fkey'), 'threads', type_='foreignkey')
    op.create_foreign_key(None, 'threads', 'mailboxes', ['mailbox_id'], ['id'], ondelete='CASCADE')
    op.drop_column('threads', 'is_read')
    op.drop_column('threads', 'contact_id')
    op.drop_column('threads', 'snippet')
    op.add_column('warmup_events', sa.Column('mailbox_id', sa.UUID(), nullable=False))
    op.add_column('warmup_events', sa.Column('target_email', sa.String(), nullable=False))
    op.add_column('warmup_events', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('warmup_events', sa.Column('body_preview', sa.Text(), nullable=True))
    op.add_column('warmup_events', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('warmup_events', sa.Column('replied_at', sa.DateTime(), nullable=True))
    op.alter_column('warmup_events', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_warmup_events_id'), table_name='warmup_events')
    op.drop_constraint(op.f('warmup_events_pair_id_fkey'), 'warmup_events', type_='foreignkey')
    op.drop_constraint(op.f('warmup_events_recipient_id_fkey'), 'warmup_events', type_='foreignkey')
    op.drop_constraint(op.f('warmup_events_sender_id_fkey'), 'warmup_events', type_='foreignkey')
    op.create_foreign_key(None, 'warmup_events', 'mailboxes', ['mailbox_id'], ['id'], ondelete='CASCADE')
    op.drop_column('warmup_events', 'recipient_id')
    op.drop_column('warmup_events', 'pair_id')
    op.drop_column('warmup_events', 'sender_id')
    op.add_column('warmup_pairs', sa.Column('sender_mailbox_id', sa.UUID(), nullable=False))
    op.add_column('warmup_pairs', sa.Column('recipient_mailbox_id', sa.UUID(), nullable=False))
    op.add_column('warmup_pairs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('warmup_pairs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('warmup_pairs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_warmup_pairs_id'), table_name='warmup_pairs')
    op.drop_constraint(op.f('warmup_pairs_mailbox_b_id_fkey'), 'warmup_pairs', type_='foreignkey')
    op.drop_constraint(op.f('warmup_pairs_mailbox_a_id_fkey'), 'warmup_pairs', type_='foreignkey')
    op.create_foreign_key(None, 'warmup_pairs', 'mailboxes', ['sender_mailbox_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'warmup_pairs', 'mailboxes', ['recipient_mailbox_id'], ['id'], ondelete='CASCADE')
    op.drop_column('warmup_pairs', 'mailbox_b_id')
    op.drop_column('warmup_pairs', 'mailbox_a_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warmup_pairs', sa.Column('mailbox_a_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('warmup_pairs', sa.Column('mailbox_b_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'warmup_pairs', type_='foreignkey')
    op.drop_constraint(None, 'warmup_pairs', type_='foreignkey')
    op.create_foreign_key(op.f('warmup_pairs_mailbox_a_id_fkey'), 'warmup_pairs', 'mailboxes', ['mailbox_a_id'], ['id'])
    op.create_foreign_key(op.f('warmup_pairs_mailbox_b_id_fkey'), 'warmup_pairs', 'mailboxes', ['mailbox_b_id'], ['id'])
    op.create_index(op.f('ix_warmup_pairs_id'), 'warmup_pairs', ['id'], unique=False)
    op.alter_column('warmup_pairs', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('warmup_pairs', 'updated_at')
    op.drop_column('warmup_pairs', 'created_at')
    op.drop_column('warmup_pairs', 'recipient_mailbox_id')
    op.drop_column('warmup_pairs', 'sender_mailbox_id')
    op.add_column('warmup_events', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('warmup_events', sa.Column('pair_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('warmup_events', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'warmup_events', type_='foreignkey')
    op.create_foreign_key(op.f('warmup_events_sender_id_fkey'), 'warmup_events', 'mailboxes', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('warmup_events_recipient_id_fkey'), 'warmup_events', 'mailboxes', ['recipient_id'], ['id'])
    op.create_foreign_key(op.f('warmup_events_pair_id_fkey'), 'warmup_events', 'warmup_pairs', ['pair_id'], ['id'])
    op.create_index(op.f('ix_warmup_events_id'), 'warmup_events', ['id'], unique=False)
    op.alter_column('warmup_events', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('warmup_events', 'replied_at')
    op.drop_column('warmup_events', 'sent_at')
    op.drop_column('warmup_events', 'body_preview')
    op.drop_column('warmup_events', 'subject')
    op.drop_column('warmup_events', 'target_email')
    op.drop_column('warmup_events', 'mailbox_id')
    op.add_column('threads', sa.Column('snippet', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('threads', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('threads', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.create_foreign_key(op.f('threads_mailbox_id_fkey'), 'threads', 'mailboxes', ['mailbox_id'], ['id'])
    op.create_foreign_key(op.f('threads_contact_id_fkey'), 'threads', 'contacts', ['contact_id'], ['id'])
    op.drop_index(op.f('ix_threads_external_thread_id'), table_name='threads')
    op.create_index(op.f('ix_threads_id'), 'threads', ['id'], unique=False)
    op.alter_column('threads', 'mailbox_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('threads', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('threads', 'created_at')
    op.drop_column('threads', 'last_message_at')
    op.drop_column('threads', 'participants')
    op.drop_column('threads', 'external_thread_id')
    op.add_column('messages', sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('html_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('text_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('is_from_me', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('to_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_thread_id_fkey'), 'messages', 'threads', ['thread_id'], ['id'])
    op.drop_index(op.f('ix_messages_message_id_header'), table_name='messages')
    op.drop_index(op.f('ix_messages_in_reply_to'), table_name='messages')
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.alter_column('messages', 'thread_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'received_at')
    op.drop_column('messages', 'status')
    op.drop_column('messages', 'references_header')
    op.drop_column('messages', 'message_id_header')
    op.drop_column('messages', 'html_body')
    op.drop_column('messages', 'text_body')
    op.drop_column('messages', 'subject')
    op.drop_column('messages', 'bcc_emails')
    op.drop_column('messages', 'cc_emails')
    op.drop_column('messages', 'to_emails')
    op.drop_column('messages', 'direction')
    op.drop_column('messages', 'mailbox_id')
    op.add_column('mailboxes', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mailboxes', sa.Column('daily_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mailboxes', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mailboxes', type_='foreignkey')
    op.create_foreign_key(op.f('mailboxes_domain_id_fkey'), 'mailboxes', 'domains', ['domain_id'], ['id'])
    op.create_index(op.f('ix_mailboxes_id'), 'mailboxes', ['id'], unique=False)
    op.alter_column('mailboxes', 'imap_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mailboxes', 'imap_host',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mailboxes', 'smtp_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mailboxes', 'smtp_host',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mailboxes', 'domain_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('mailboxes', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('mailboxes', 'updated_at')
    op.drop_column('mailboxes', 'status')
    op.drop_column('mailboxes', 'current_warmup_stage')
    op.drop_column('mailboxes', 'daily_send_limit')
    op.drop_column('mailboxes', 'imap_password_encrypted')
    op.drop_column('mailboxes', 'imap_username')
    op.drop_column('mailboxes', 'smtp_password_encrypted')
    op.drop_column('mailboxes', 'smtp_username')
    op.drop_column('mailboxes', 'display_name')
    op.add_column('domains', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.alter_column('domains', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('domains', 'updated_at')
    op.drop_column('domains', 'mx_status')
    op.drop_column('domains', 'dmarc_status')
    op.drop_column('domains', 'dkim_status')
    op.drop_column('domains', 'spf_status')
    op.drop_column('domains', 'status')
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.alter_column('contacts', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('NEW', 'CONTACTED', 'REPLIED', 'UNSUBSCRIBED', name='contactstatus'),
               existing_nullable=True)
    op.alter_column('contacts', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'notes')
    op.drop_column('contacts', 'source')
    op.add_column('campaigns', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('body_template', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('subject_template', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_mailbox_id_fkey'), 'campaigns', 'mailboxes', ['mailbox_id'], ['id'])
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.alter_column('campaigns', 'mailbox_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('campaigns', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('campaigns', 'updated_at')
    op.drop_column('campaigns', 'template_body')
    op.drop_column('campaigns', 'template_subject')
    op.drop_column('campaigns', 'status')
    op.drop_constraint(None, 'campaign_leads', type_='foreignkey')
    op.drop_constraint(None, 'campaign_leads', type_='foreignkey')
    op.create_foreign_key(op.f('campaign_leads_contact_id_fkey'), 'campaign_leads', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(op.f('campaign_leads_campaign_id_fkey'), 'campaign_leads', 'campaigns', ['campaign_id'], ['id'])
    op.create_index(op.f('ix_campaign_leads_id'), 'campaign_leads', ['id'], unique=False)
    op.alter_column('campaign_leads', 'contact_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('campaign_leads', 'campaign_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('campaign_leads', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('campaign_leads', 'updated_at')
    op.drop_column('campaign_leads', 'created_at')
    op.drop_column('campaign_leads', 'replied_at')
    op.drop_column('campaign_leads', 'scheduled_at')
    op.add_column('ai_summaries', sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('ai_summaries', sa.Column('intent_classification', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ai_summaries', type_='foreignkey')
    op.create_foreign_key(op.f('ai_summaries_thread_id_fkey'), 'ai_summaries', 'threads', ['thread_id'], ['id'])
    op.create_index(op.f('ix_ai_summaries_id'), 'ai_summaries', ['id'], unique=False)
    op.alter_column('ai_summaries', 'thread_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_summaries', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('ai_summaries', 'updated_at')
    op.drop_column('ai_summaries', 'extracted_entities')
    op.drop_column('ai_summaries', 'tone')
    op.drop_column('ai_summaries', 'intent')
    op.drop_column('ai_summaries', 'summary')
    op.drop_table('send_logs')
    # ### end Alembic commands ###
