"""Part 4: Core Telemetry Schema Extensions

Revision ID: 6c5b069ae5dc
Revises: 06cb5b0641da
Create Date: 2026-03-28 04:06:21.957945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5b069ae5dc'
down_revision: Union[str, Sequence[str], None] = '06cb5b0641da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata_blob', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('job_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('payload_summary', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_logs_idempotency_key'), 'job_logs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_job_logs_job_id'), 'job_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_logs_job_type'), 'job_logs', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_logs_status'), 'job_logs', ['status'], unique=False)
    op.create_table('suppression_list',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_list_email'), 'suppression_list', ['email'], unique=True)
    op.create_table('system_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_alerts_alert_type'), 'system_alerts', ['alert_type'], unique=False)
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_name', sa.String(), nullable=False),
    sa.Column('worker_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_blob', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_heartbeats_worker_name'), 'worker_heartbeats', ['worker_name'], unique=False)
    op.create_table('campaign_preflight_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('check_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata_blob', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_preflight_checks_campaign_id'), 'campaign_preflight_checks', ['campaign_id'], unique=False)
    op.create_table('deliverability_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mailbox_id', sa.UUID(), nullable=True),
    sa.Column('domain_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('smtp_response', sa.Text(), nullable=True),
    sa.Column('metadata_blob', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverability_events_event_type'), 'deliverability_events', ['event_type'], unique=False)
    op.create_table('email_verification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('syntax_valid', sa.Boolean(), nullable=True),
    sa.Column('domain_valid', sa.Boolean(), nullable=True),
    sa.Column('mx_valid', sa.Boolean(), nullable=True),
    sa.Column('disposable', sa.Boolean(), nullable=True),
    sa.Column('role_based', sa.Boolean(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('suppressed', sa.Boolean(), nullable=True),
    sa.Column('smtp_check_result', sa.String(), nullable=True),
    sa.Column('catch_all_result', sa.String(), nullable=True),
    sa.Column('verification_score', sa.Integer(), nullable=True),
    sa.Column('final_status', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_logs_email'), 'email_verification_logs', ['email'], unique=False)
    op.add_column('contacts', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('website', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('country', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('email_status', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('verification_score', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('is_disposable', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('is_role_based', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('is_suppressed', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('source_file_name', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('source_import_job_id', sa.UUID(), nullable=True))
    op.add_column('contacts', sa.Column('last_verified_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('last_contacted_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('last_replied_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('tags', sa.String(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'lead_import_jobs', ['source_import_job_id'], ['id'], ondelete='SET NULL')
    op.drop_column('contacts', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'tags')
    op.drop_column('contacts', 'last_replied_at')
    op.drop_column('contacts', 'last_contacted_at')
    op.drop_column('contacts', 'last_verified_at')
    op.drop_column('contacts', 'source_import_job_id')
    op.drop_column('contacts', 'source_file_name')
    op.drop_column('contacts', 'is_suppressed')
    op.drop_column('contacts', 'is_role_based')
    op.drop_column('contacts', 'is_disposable')
    op.drop_column('contacts', 'verification_score')
    op.drop_column('contacts', 'email_status')
    op.drop_column('contacts', 'phone')
    op.drop_column('contacts', 'linkedin_url')
    op.drop_column('contacts', 'country')
    op.drop_column('contacts', 'website')
    op.drop_column('contacts', 'job_title')
    op.drop_index(op.f('ix_email_verification_logs_email'), table_name='email_verification_logs')
    op.drop_table('email_verification_logs')
    op.drop_index(op.f('ix_deliverability_events_event_type'), table_name='deliverability_events')
    op.drop_table('deliverability_events')
    op.drop_index(op.f('ix_campaign_preflight_checks_campaign_id'), table_name='campaign_preflight_checks')
    op.drop_table('campaign_preflight_checks')
    op.drop_index(op.f('ix_worker_heartbeats_worker_name'), table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_index(op.f('ix_system_alerts_alert_type'), table_name='system_alerts')
    op.drop_table('system_alerts')
    op.drop_index(op.f('ix_suppression_list_email'), table_name='suppression_list')
    op.drop_table('suppression_list')
    op.drop_index(op.f('ix_job_logs_status'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_job_type'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_job_id'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_idempotency_key'), table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
